PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户模块
    url(r'^Region/', include('apps.Region.urls', namespace='Region')),  # 区域模块
    url(r'^SpaceInfo/', include('apps.SpaceInfo.urls', namespace='SpaceInfo')),  # 停车位模块
    url(r'^Car/', include('apps.Car.urls', namespace='Car')),  # 车辆模块
    url(r'^CarModel/', include('apps.CarModel.urls', namespace='CarModel')),  # 车型模块
    url(r'^Park/', include('apps.Park.urls', namespace='Park')),  # 车辆停车模块
    url(r'^SpaceOrder/', include('apps.SpaceOrder.urls', namespace='SpaceOrder')),  # 车位预约模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/CarModel/urls.py
from apps.CarModel.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'CarModel'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<modelId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<modelId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<modelId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<modelId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/CarModel/models.py
from django.db import models


class CarModel(models.Model):
    modelId = models.AutoField(primary_key=True, verbose_name='车型id')
    modelName = models.CharField(max_length=20, default='', verbose_name='车型名称')

    class Meta:
        db_table = 't_CarModel'
        verbose_name = '车型信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        carModel = {
            'modelId': self.modelId,
            'modelName': self.modelName,
        }
        return carModel


PythonProject/apps/CarModel/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.CarModel.models import CarModel
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台车型添加
    def get(self,request):

        # 使用模板
        return render(request, 'CarModel/carModel_frontAdd.html')

    def post(self, request):
        carModel = CarModel() # 新建一个车型对象然后获取参数
        carModel.modelName = request.POST.get('carModel.modelName')
        carModel.save() # 保存车型信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改车型
    def get(self, request, modelId):
        context = {'modelId': modelId}
        return render(request, 'CarModel/carModel_frontModify.html', context)


class FrontListView(BaseView):  # 前台车型查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        # 然后条件组合查询过滤
        carModels = CarModel.objects.all()
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(carModels, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        carModels_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'carModels_page': carModels_page,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'CarModel/carModel_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示车型详情页
    def get(self, request, modelId):
        # 查询需要显示的车型对象
        carModel = CarModel.objects.get(modelId=modelId)
        context = {
            'carModel': carModel
        }
        # 渲染模板显示
        return render(request, 'CarModel/carModel_frontshow.html', context)


class ListAllView(View): # 前台查询所有车型
    def get(self,request):
        carModels = CarModel.objects.all()
        carModelList = []
        for carModel in carModels:
            carModelObj = {
                'modelId': carModel.modelId,
                'modelName': carModel.modelName,
            }
            carModelList.append(carModelObj)
        return JsonResponse(carModelList, safe=False)


class UpdateView(BaseView):  # Ajax方式车型更新
    def get(self, request, modelId):
        # GET方式请求查询车型对象并返回车型json格式
        carModel = CarModel.objects.get(modelId=modelId)
        return JsonResponse(carModel.getJsonObj())

    def post(self, request, modelId):
        # POST方式提交车型修改信息更新到数据库
        carModel = CarModel.objects.get(modelId=modelId)
        carModel.modelName = request.POST.get('carModel.modelName')
        carModel.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台车型添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'CarModel/carModel_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        carModel = CarModel() # 新建一个车型对象然后获取参数
        carModel.modelName = request.POST.get('carModel.modelName')
        carModel.save() # 保存车型信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新车型
    def get(self, request, modelId):
        context = {'modelId': modelId}
        return render(request, 'CarModel/carModel_modify.html', context)


class ListView(BaseView):  # 后台车型列表
    def get(self, request):
        # 使用模板
        return render(request, 'CarModel/carModel_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        # 然后条件组合查询过滤
        carModels = CarModel.objects.all()
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(carModels, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        carModels_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        carModelList = []
        for carModel in carModels_page:
            carModel = carModel.getJsonObj()
            carModelList.append(carModel)
        # 构造模板页面需要的参数
        carModel_res = {
            'rows': carModelList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(carModel_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除车型信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        modelIds = self.getStrParam(request, 'modelIds')
        modelIds = modelIds.split(',')
        count = 0
        try:
            for modelId in modelIds:
                CarModel.objects.get(modelId=modelId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出车型信息到excel并下载
    def get(self, request):
        # 收集查询参数
        # 然后条件组合查询过滤
        carModels = CarModel.objects.all()
        #将查询结果集转换成列表
        carModelList = []
        for carModel in carModels:
            carModel = carModel.getJsonObj()
            carModelList.append(carModel)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(carModelList)
        # 设置要导入到excel的列
        columns_map = {
            'modelId': '车型id',
            'modelName': '车型名称',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'carModels.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="carModels.xlsx"'
        return response


PythonProject/templates/CarModel/carModel_add.html
{% include 'check_logstate.html' %}
{% load staticfiles %}

 <link rel="stylesheet" type="text/css" href="{% static 'css/carModel.css' %}" />
<div id="carModelAddDiv">
    {% csrf_token %}
	<form id="carModelAddForm" enctype="multipart/form-data"  method="post">
		<div>
			<span class="label">车型名称:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="carModel_modelName" name="carModel.modelName" style="width:200px" />

			</span>

		</div>
		<div class="operation">
			<a id="carModelAddButton" class="easyui-linkbutton">添加</a>
			<a id="carModelClearButton" class="easyui-linkbutton">重填</a>
		</div> 
	</form>
</div>
<script src="{% static 'js/CarModel/carModel_add.js' %}"></script>

PythonProject/templates/CarModel/carModel_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>车型添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
	<div class="row">
		<div class="col-md-12 wow fadeInUp" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li role="presentation" ><a href="{% url 'CarModel:frontList' %}">车型列表</a></li>
			    	<li role="presentation" class="active"><a href="#carModelAdd" aria-controls="carModelAdd" role="tab" data-toggle="tab">添加车型</a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
				    <div role="tabpanel" class="tab-pane" id="carModelList">
				    </div>
				    <div role="tabpanel" class="tab-pane active" id="carModelAdd"> 
				      	<form class="form-horizontal" name="carModelAddForm" id="carModelAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
						  <div class="form-group">
						  	 <label for="carModel_modelName" class="col-md-2 text-right">车型名称:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="carModel_modelName" name="carModel.modelName" class="form-control" placeholder="请输入车型名称">
							 </div>
						  </div>
				          <div class="form-group">
				             <span class="col-md-2"></span>
				             <span onclick="ajaxCarModelAdd();" class="btn btn-primary bottom5 top5">添加</span>
				          </div>
						</form> 
				        <style>#carModelAddForm .form-group {margin:10px;}  </style>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>

{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
	//提交添加车型信息
	function ajaxCarModelAdd() { 
		//提交之前先验证表单
		$("#carModelAddForm").data('bootstrapValidator').validate();
		if(!$("#carModelAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'CarModel:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#carModelAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证车型添加表单字段
	$('#carModelAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"carModel.modelName": {
				validators: {
					notEmpty: {
						message: "车型名称不能为空",
					}
				}
			},
		}
	}); 
})
</script>
</body>
</html>

PythonProject/templates/CarModel/carModel_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>车型查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div style="display:none;">
		<div class="page-header">
    		<h1>车型查询</h1>
		</div>
		<form name="carModelQueryForm" id="carModelQueryForm" action="{% url 'CarModel:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#carModelListPanel" aria-controls="carModelListPanel" role="tab" data-toggle="tab">车型列表</a></li>
			    	<li role="presentation" ><a href="{% url 'CarModel:frontAdd' %}" style="display:none;">添加车型</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="carModelListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>车型id</td><td>车型名称</td><td>操作</td></tr>
                                        {% for carModel in carModels_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ carModel.modelId }}</td>
 											<td>{{ carModel.modelName }}</td>
 											<td>
 												<a href="{% url 'CarModel:frontShow' carModel.modelId  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="carModelEdit('{{ carModel.modelId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="carModelDelete('{{ carModel.modelId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="carModelEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;车型信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="carModelEditForm" id="carModelEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="carModel_modelId_edit" class="col-md-3 text-right">车型id:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="carModel_modelId_edit" name="carModel.modelId" class="form-control" placeholder="请输入车型id" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="carModel_modelName_edit" class="col-md-3 text-right">车型名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="carModel_modelName_edit" name="carModel.modelName" class="form-control" placeholder="请输入车型名称">
			 </div>
		  </div>
		</form> 
	    <style>#carModelEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxCarModelModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.carModelQueryForm.currentPage.value = currentPage;
    document.carModelQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.carModelQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.carModelQueryForm.currentPage.value = pageValue;
    documentcarModelQueryForm.submit();
}

/*弹出修改车型界面并初始化数据*/
function carModelEdit(modelId) {
	$.ajax({
		url :  '/CarModel/update/' + modelId,
		type : "get",
		dataType: "json",
		success : function (carModel, response, status) {
			if (carModel) {
				$("#carModel_modelId_edit").val(carModel.modelId);
				$("#carModel_modelName_edit").val(carModel.modelName);
				$('#carModelEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除车型信息*/
function carModelDelete(modelId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/CarModel/deletes",
			data : {
				modelIds : modelId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#carModelQueryForm").submit();
					//location.href= basePath + "CarModel/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交车型信息表单给服务器端修改*/
function ajaxCarModelModify() {
	$.ajax({
		url :   '/CarModel/update/' + $("#carModel_modelId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#carModelEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                location.href= basePath + "CarModel/frontlist";
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>


PythonProject/templates/CarModel/carModel_frontshow.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <TITLE>查看车型详情</TITLE>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;"> 
{% include 'header.html' %}
<div class="container">
	<ul class="breadcrumb">
  		<li><a href={% url 'Index:index' %}">首页</a></li>
  		<li><a href="{% url 'CarModel:frontList' %}">车型信息</a></li>
  		<li class="active">详情查看</li>
	</ul>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">车型id:</div>
		<div class="col-md-10 col-xs-6">{{ carModel.modelId }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">车型名称:</div>
		<div class="col-md-10 col-xs-6">{{ carModel.modelName }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4"></div>
		<div class="col-md-6 col-xs-6">
			<button onclick="history.back();" class="btn btn-primary">返回</button>
		</div>
	</div>
</div> 
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
$(function(){
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function(){
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();
 })
 </script> 
</body>
</html>
