PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户模块
    url(r'^Region/', include('apps.Region.urls', namespace='Region')),  # 区域模块
    url(r'^SpaceInfo/', include('apps.SpaceInfo.urls', namespace='SpaceInfo')),  # 停车位模块
    url(r'^Car/', include('apps.Car.urls', namespace='Car')),  # 车辆模块
    url(r'^CarModel/', include('apps.CarModel.urls', namespace='CarModel')),  # 车型模块
    url(r'^Park/', include('apps.Park.urls', namespace='Park')),  # 车辆停车模块
    url(r'^SpaceOrder/', include('apps.SpaceOrder.urls', namespace='SpaceOrder')),  # 车位预约模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/Region/urls.py
from apps.Region.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'Region'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<regionId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<regionId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<regionId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<regionId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Region/models.py
from django.db import models


class Region(models.Model):
    regionId = models.AutoField(primary_key=True, verbose_name='区域id')
    regionFloor = models.CharField(max_length=20, default='', verbose_name='所在楼层')
    regionName = models.CharField(max_length=20, default='', verbose_name='区域名称')
    regionDesc = models.CharField(max_length=800, default='', verbose_name='区域说明')

    class Meta:
        db_table = 't_Region'
        verbose_name = '区域信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        region = {
            'regionId': self.regionId,
            'regionFloor': self.regionFloor,
            'regionName': self.regionName,
            'regionDesc': self.regionDesc,
        }
        return region


PythonProject/apps/Region/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.Region.models import Region
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台区域添加
    def get(self,request):

        # 使用模板
        return render(request, 'Region/region_frontAdd.html')

    def post(self, request):
        region = Region() # 新建一个区域对象然后获取参数
        region.regionFloor = request.POST.get('region.regionFloor')
        region.regionName = request.POST.get('region.regionName')
        region.regionDesc = request.POST.get('region.regionDesc')
        region.save() # 保存区域信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改区域
    def get(self, request, regionId):
        context = {'regionId': regionId}
        return render(request, 'Region/region_frontModify.html', context)


class FrontListView(BaseView):  # 前台区域查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        regionFloor = self.getStrParam(request, 'regionFloor')
        # 然后条件组合查询过滤
        regions = Region.objects.all()
        if regionFloor != '':
            regions = regions.filter(regionFloor__contains=regionFloor)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(regions, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        regions_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'regions_page': regions_page,
            'regionFloor': regionFloor,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Region/region_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示区域详情页
    def get(self, request, regionId):
        # 查询需要显示的区域对象
        region = Region.objects.get(regionId=regionId)
        context = {
            'region': region
        }
        # 渲染模板显示
        return render(request, 'Region/region_frontshow.html', context)


class ListAllView(View): # 前台查询所有区域
    def get(self,request):
        regions = Region.objects.all()
        regionList = []
        for region in regions:
            regionObj = {
                'regionId': region.regionId,
                'regionName': region.regionName,
            }
            regionList.append(regionObj)
        return JsonResponse(regionList, safe=False)


class UpdateView(BaseView):  # Ajax方式区域更新
    def get(self, request, regionId):
        # GET方式请求查询区域对象并返回区域json格式
        region = Region.objects.get(regionId=regionId)
        return JsonResponse(region.getJsonObj())

    def post(self, request, regionId):
        # POST方式提交区域修改信息更新到数据库
        region = Region.objects.get(regionId=regionId)
        region.regionFloor = request.POST.get('region.regionFloor')
        region.regionName = request.POST.get('region.regionName')
        region.regionDesc = request.POST.get('region.regionDesc')
        region.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台区域添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'Region/region_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        region = Region() # 新建一个区域对象然后获取参数
        region.regionFloor = request.POST.get('region.regionFloor')
        region.regionName = request.POST.get('region.regionName')
        region.regionDesc = request.POST.get('region.regionDesc')
        region.save() # 保存区域信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新区域
    def get(self, request, regionId):
        context = {'regionId': regionId}
        return render(request, 'Region/region_modify.html', context)


class ListView(BaseView):  # 后台区域列表
    def get(self, request):
        # 使用模板
        return render(request, 'Region/region_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        regionFloor = self.getStrParam(request, 'regionFloor')
        # 然后条件组合查询过滤
        regions = Region.objects.all()
        if regionFloor != '':
            regions = regions.filter(regionFloor__contains=regionFloor)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(regions, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        regions_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        regionList = []
        for region in regions_page:
            region = region.getJsonObj()
            regionList.append(region)
        # 构造模板页面需要的参数
        region_res = {
            'rows': regionList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(region_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除区域信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        regionIds = self.getStrParam(request, 'regionIds')
        regionIds = regionIds.split(',')
        count = 0
        try:
            for regionId in regionIds:
                Region.objects.get(regionId=regionId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出区域信息到excel并下载
    def get(self, request):
        # 收集查询参数
        regionFloor = self.getStrParam(request, 'regionFloor')
        # 然后条件组合查询过滤
        regions = Region.objects.all()
        if regionFloor != '':
            regions = regions.filter(regionFloor__contains=regionFloor)
        #将查询结果集转换成列表
        regionList = []
        for region in regions:
            region = region.getJsonObj()
            regionList.append(region)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(regionList)
        # 设置要导入到excel的列
        columns_map = {
            'regionId': '区域id',
            'regionFloor': '所在楼层',
            'regionName': '区域名称',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'regions.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="regions.xlsx"'
        return response


PythonProject/templates/Region/region_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>区域添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
	<div class="row">
		<div class="col-md-12 wow fadeInUp" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li role="presentation" ><a href="{% url 'Region:frontList' %}">区域列表</a></li>
			    	<li role="presentation" class="active"><a href="#regionAdd" aria-controls="regionAdd" role="tab" data-toggle="tab">添加区域</a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
				    <div role="tabpanel" class="tab-pane" id="regionList">
				    </div>
				    <div role="tabpanel" class="tab-pane active" id="regionAdd"> 
				      	<form class="form-horizontal" name="regionAddForm" id="regionAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
						  <div class="form-group">
						  	 <label for="region_regionFloor" class="col-md-2 text-right">所在楼层:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="region_regionFloor" name="region.regionFloor" class="form-control" placeholder="请输入所在楼层">
							 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="region_regionName" class="col-md-2 text-right">区域名称:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="region_regionName" name="region.regionName" class="form-control" placeholder="请输入区域名称">
							 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="region_regionDesc" class="col-md-2 text-right">区域说明:</label>
						  	 <div class="col-md-8">
							    <textarea id="region_regionDesc" name="region.regionDesc" rows="8" class="form-control" placeholder="请输入区域说明"></textarea>
							 </div>
						  </div>
				          <div class="form-group">
				             <span class="col-md-2"></span>
				             <span onclick="ajaxRegionAdd();" class="btn btn-primary bottom5 top5">添加</span>
				          </div>
						</form> 
				        <style>#regionAddForm .form-group {margin:10px;}  </style>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>

{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
	//提交添加区域信息
	function ajaxRegionAdd() { 
		//提交之前先验证表单
		$("#regionAddForm").data('bootstrapValidator').validate();
		if(!$("#regionAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'Region:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#regionAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证区域添加表单字段
	$('#regionAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"region.regionFloor": {
				validators: {
					notEmpty: {
						message: "所在楼层不能为空",
					}
				}
			},
			"region.regionName": {
				validators: {
					notEmpty: {
						message: "区域名称不能为空",
					}
				}
			},
		}
	}); 
})
</script>
</body>
</html>

PythonProject/templates/Region/region_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>区域查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>区域查询</h1>
		</div>
		<form name="regionQueryForm" id="regionQueryForm" action="{% url 'Region:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
			<div class="form-group">
				<label for="regionFloor">所在楼层:</label>
				<input type="text" id="regionFloor" name="regionFloor" value="{{ regionFloor }}" class="form-control" placeholder="请输入所在楼层">
			</div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-9 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#regionListPanel" aria-controls="regionListPanel" role="tab" data-toggle="tab">区域列表</a></li>
			    	<li role="presentation" ><a href="{% url 'Region:frontAdd' %}" style="display:none;">添加区域</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="regionListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>区域id</td><td>所在楼层</td><td>区域名称</td><td>操作</td></tr>
                                        {% for region in regions_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ region.regionId }}</td>
 											<td>{{ region.regionFloor }}</td>
 											<td>{{ region.regionName }}</td>
 											<td>
 												<a href="/SpaceInfo/frontList?regionObj.regionId={{ region.regionId }}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="regionEdit('{{ region.regionId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="regionDelete('{{ region.regionId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="regionEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;区域信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="regionEditForm" id="regionEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="region_regionId_edit" class="col-md-3 text-right">区域id:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="region_regionId_edit" name="region.regionId" class="form-control" placeholder="请输入区域id" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="region_regionFloor_edit" class="col-md-3 text-right">所在楼层:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="region_regionFloor_edit" name="region.regionFloor" class="form-control" placeholder="请输入所在楼层">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="region_regionName_edit" class="col-md-3 text-right">区域名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="region_regionName_edit" name="region.regionName" class="form-control" placeholder="请输入区域名称">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="region_regionDesc_edit" class="col-md-3 text-right">区域说明:</label>
		  	 <div class="col-md-9">
			    <textarea id="region_regionDesc_edit" name="region.regionDesc" rows="8" class="form-control" placeholder="请输入区域说明"></textarea>
			 </div>
		  </div>
		</form> 
	    <style>#regionEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxRegionModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.regionQueryForm.currentPage.value = currentPage;
    document.regionQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.regionQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.regionQueryForm.currentPage.value = pageValue;
    documentregionQueryForm.submit();
}

/*弹出修改区域界面并初始化数据*/
function regionEdit(regionId) {
	$.ajax({
		url :  '/Region/update/' + regionId,
		type : "get",
		dataType: "json",
		success : function (region, response, status) {
			if (region) {
				$("#region_regionId_edit").val(region.regionId);
				$("#region_regionFloor_edit").val(region.regionFloor);
				$("#region_regionName_edit").val(region.regionName);
				$("#region_regionDesc_edit").val(region.regionDesc);
				$('#regionEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除区域信息*/
function regionDelete(regionId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/Region/deletes",
			data : {
				regionIds : regionId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#regionQueryForm").submit();
					//location.href= basePath + "Region/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交区域信息表单给服务器端修改*/
function ajaxRegionModify() {
	$.ajax({
		url :   '/Region/update/' + $("#region_regionId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#regionEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#regionQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>
